<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; color: #333; margin: 0; padding: 20px; }
        .ticket { border: 2px dashed #06b6d4; border-radius: 12px; overflow: hidden; position: relative; }
        .header { background: #06b6d4; color: #fff; padding: 20px; text-align: center; }
        .event-name { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
        .event-date { font-size: 14px; opacity: 0.9; }
        .body { padding: 20px; text-align: center; }
        .attendee { font-size: 18px; font-weight: bold; margin-bottom: 20px; }
        .details { display: table; width: 100%; border-top: 1px solid #eee; padding-top: 20px; }
        .details-col { display: table-cell; width: 33%; text-align: center; }
        .label { font-size: 10px; color: #999; text-transform: uppercase; margin-bottom: 5px; }
        .value { font-size: 14px; font-weight: bold; }
        .qr-placeholder { width: 120px; height: 120px; border: 1px solid #eee; margin: 20px auto; padding: 10px; }
        .ref { font-family: monospace; font-size: 12px; color: #999; margin-top: 10px; }
        .footer { background: #f8fafc; padding: 15px; font-size: 10px; color: #999; text-align: center; }
    </style>
</head>
<body>
    <div class="ticket">
        <div class="header">
            <div class="event-name">{{ $event_name }}</div>
            <div class="event-date">{{ $event_date }}</div>
        </div>
        <div class="body">
            <div class="label">Attendee</div>
            <div class="attendee">{{ $attendee_name }}</div>
            
            <div class="qr-placeholder">
                <!-- In a real app, a QR code image would be here -->
                <div style="width: 100%; height: 100%; background: #000; color: #fff; display: flex; align-items: center; justify-content: center; font-size: 8px;">
                    SECURE QR CODE<br>{{ $reference }}
                </div>
            </div>
            
            <div class="ref">REF: {{ $reference }}</div>
        </div>
        <div class="details">
            <div class="details-col">
                <div class="label">Type</div>
                <div class="value" style="text-transform: uppercase;">{{ $ticket_type }}</div>
            </div>
            <div class="details-col">
                <div class="label">Quantity</div>
                <div class="value">{{ $quantity }}</div>
            </div>
            <div class="details-col">
                <div class="label">Status</div>
                <div class="value" style="color: #10b981;">VERIFIED</div>
            </div>
        </div>
        <div class="footer">
            Please present this ticket at the entry point. Admission is subject to terms and conditions.
            Generated by Fuwa.NG Tickets &copy; {{ date('Y') }}
        </div>
    </div>
</body>
</html>
