<?php

return [
    'service_types' => [
        'vtu_airtime' => [
            'label' => 'Airtime',
            'direction' => 'debit',
            'order_type' => 'Airtime Purchase',
            'tx_prefix' => 'VTU',
            'limits' => ['min' => 50, 'max' => 50000],
            'rules' => [
                'network' => ['required', 'string'],
                'amount' => ['required', 'numeric', 'min:50'],
                'phone' => ['required', 'string', 'digits:11'],
            ],
        ],
        'vtu_data' => [
            'label' => 'Data Bundles',
            'direction' => 'debit',
            'order_type' => 'Data Purchase',
            'tx_prefix' => 'DATA',
            'limits' => ['min' => 50, 'max' => 500000],
            'rules' => [
                'network' => ['required', 'string'],
                'plan_id' => ['required', 'string'],
                'amount' => ['required', 'numeric', 'min:50'],
                'phone' => ['required', 'string', 'digits:11'],
            ],
        ],
        'vtu_cable_tv' => [
            'label' => 'Cable TV',
            'direction' => 'debit',
            'order_type' => 'Cable TV Subscription',
            'tx_prefix' => 'CABLE',
            'limits' => ['min' => 100, 'max' => 500000],
            'rules' => [
                'serviceID' => ['required', 'string'],
                'variation_code' => ['required', 'string'],
                'smart_card_number' => ['required', 'string'],
                'amount' => ['required', 'numeric', 'min:100'],
                'phone' => ['required', 'string', 'digits:11'],
            ],
        ],
        'vtu_electricity' => [
            'label' => 'Electricity Bills',
            'direction' => 'debit',
            'order_type' => 'Electricity Bill',
            'tx_prefix' => 'ELEC',
            'limits' => ['min' => 500, 'max' => 1000000],
            'rules' => [
                'serviceID' => ['required', 'string'],
                'variation_code' => ['required', 'string'],
                'meter_number' => ['required', 'string'],
                'amount' => ['required', 'numeric', 'min:500'],
                'phone' => ['required', 'string', 'digits:11'],
            ],
            'validation_rules' => [
                'serviceID' => ['required', 'string'],
                'variation_code' => ['required', 'string'],
                'meter_number' => ['required', 'string'],
            ],
        ],
        'vtu_airtime_to_cash' => [
            'label' => 'Airtime to Cash',
            'direction' => 'credit',
            'order_type' => 'Airtime to Cash',
            'tx_prefix' => 'A2C',
            'limits' => ['min' => 200, 'max' => 200000],
            'rules' => [
                'network' => ['required', 'string'],
                'amount' => ['required', 'numeric', 'min:200'],
                'phone' => ['required', 'string', 'digits:11'],
                'bank_code' => ['required', 'string'],
                'account_number' => ['required', 'string', 'digits:10'],
                'account_name' => ['nullable', 'string', 'max:120'],
            ],
        ],
        'vtu_internet' => [
            'label' => 'Internet Subscription',
            'direction' => 'debit',
            'order_type' => 'Internet Subscription',
            'tx_prefix' => 'NET',
            'limits' => ['min' => 100, 'max' => 500000],
            'rules' => [
                'serviceID' => ['required', 'string'],
                'variation_code' => ['required', 'string'],
                'customer_id' => ['required', 'string'],
                'amount' => ['required', 'numeric', 'min:100'],
                'phone' => ['required', 'string', 'digits:11'],
            ],
        ],
        'vtu_betting' => [
            'label' => 'Betting Wallet Funding',
            'direction' => 'debit',
            'order_type' => 'Betting Funding',
            'tx_prefix' => 'BET',
            'limits' => ['min' => 100, 'max' => 500000],
            'rules' => [
                'serviceID' => ['required', 'string'],
                'customer_id' => ['required', 'string'],
                'amount' => ['required', 'numeric', 'min:100'],
                'phone' => ['required', 'string', 'digits:11'],
            ],
        ],
        'vtu_epin' => [
            'label' => 'ePINs',
            'direction' => 'debit',
            'order_type' => 'ePIN Purchase',
            'tx_prefix' => 'EPIN',
            'limits' => ['min' => 100, 'max' => 500000],
            'rules' => [
                'serviceID' => ['required', 'string'],
                'variation_code' => ['required', 'string'],
                'quantity' => ['required', 'integer', 'min:1', 'max:50'],
                'amount' => ['required', 'numeric', 'min:100'],
                'phone' => ['required', 'string', 'digits:11'],
            ],
        ],
    ],
];
